# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "alpha"

# URL
baseurl:            "/Blog"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown
# markdown:           rdiscount

# Navigation
nav:
  - name:           "github"
    href:           "//github.com/AlphaXiao"
  # - name:           "category"
  #   href:           "/Blog/categories"

# Sass
sass:
  style:            :compressed
  
highlighter: rouge

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


